CREATE TABLE TEST (
	ID INT,
	NAME VARCHAR(40), 
	ADDRESS VARCHAR(70)
)


SELECT * FROM TEST

INSERT INTO TEST (ID, NAME, ADDRESS) VALUES (2, 'Panna', 'X utca')
INSERT INTO TEST (ID, NAME, ADDRESS) VALUES (3, 'Anna', 'Y utca')

UPDATE TEST SET NAME = 'Laci' WHERE ID = 2

DELETE FROM TEST WHERE ID = 2