name = input("Whats is your name?")
age = input("How old are you?")
experince = input("How many years do you have in python?")
print(f"My character is " + age + (" years old.His/her name is " + name + " and he/she has " + experince + " years experince."))
results = int(age)
results = int(experince)
print(type(results))
